/** Tiny neutral blur placeholder for product gallery images (10×8 JPEG). */
export const PRODUCT_IMAGE_BLUR_DATA_URL =
  "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxISEhUSEhIVFhUVFRUYFRgYFxUVFRUXFxUXFxUYHSggGBolGxUVITEhJSkrLi4uFx8zODMsNygtLisBCgoKDg0OGxAQGy0lHyUtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLf/AABEIAAgACAMBIgACEQEDEQH/xAAXAAADAQAAAAAAAAAAAAAAAAAAAQID/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEAMQAAAA0f8A/8QAFBABAAAAAAAAAAAAAAAAAAAAAP/aAAgBAQABPxA//8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAgBAgEBPxB//8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAgBAwEBPxB//9k=";

export const PRODUCT_GALLERY_MAIN_SIZES =
  "(max-width: 1024px) 100vw, (max-width: 1280px) 55vw, 640px";

export const PRODUCT_GALLERY_THUMB_SIZES = "120px";

export const PRODUCT_CARD_GALLERY_SIZES =
  "(max-width: 768px) 100vw, (max-width: 1280px) 50vw, 33vw";
