import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { getCompanyProfile } from "@/lib/company-profile";
import { buildCustomerPdfLines } from "@/lib/customer-display";
import { formatModuleCode } from "@/lib/format-module-code";
import { statusLabel } from "@/lib/order-display";
import type { OrderWithCustomer } from "@/types/orders";

function formatPdfCurrency(value: number) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(value);
}

function formatPdfDate(value: string) {
  return new Intl.DateTimeFormat("en-US", {
    dateStyle: "long",
    timeStyle: "short",
  }).format(new Date(value));
}

function buildOrderPdfDocument(order: OrderWithCustomer) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const company = getCompanyProfile();

  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text(company.name, 14, 20);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(90);
  doc.text("Order Quote / Invoice", 14, 28);
  doc.setTextColor(0);

  doc.setFontSize(10);
  doc.text(`Order #${order.id}`, pageWidth - 14, 20, { align: "right" });
  doc.text(`Date: ${formatPdfDate(order.createdAt)}`, pageWidth - 14, 26, {
    align: "right",
  });
  doc.text(`Status: ${statusLabel(order.status)}`, pageWidth - 14, 32, {
    align: "right",
  });

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Customer", 14, 45);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);

  const customerLines = buildCustomerPdfLines(order.customer);
  let customerY = 52;

  customerLines.forEach((line, index) => {
    const isCompanyName = index === 0 && order.customer.companyName.length > 0;

    if (isCompanyName) {
      doc.setFont("helvetica", "bold");
    } else {
      doc.setFont("helvetica", "normal");
    }

    doc.text(line, 14, customerY);
    customerY += 6;
  });

  const tableStartY = customerY + 4;

  autoTable(doc, {
    startY: tableStartY,
    head: [["Module Code", "Qty", "Unit Price", "Line Total"]],
    body: order.items.map((item) => [
      formatModuleCode(item),
      String(item.quantity),
      formatPdfCurrency(item.unitPrice),
      formatPdfCurrency(item.unitPrice * item.quantity),
    ]),
    headStyles: {
      fillColor: [41, 37, 36],
      textColor: 255,
      fontStyle: "bold",
    },
    styles: {
      fontSize: 9,
      cellPadding: 4,
      overflow: "linebreak",
    },
    columnStyles: {
      0: { cellWidth: 95 },
      1: { halign: "center", cellWidth: 18 },
      2: { halign: "right", cellWidth: 32 },
      3: { halign: "right", cellWidth: 32 },
    },
  });

  const finalY = doc.lastAutoTable?.finalY ?? tableStartY;
  const pricing = order.pricing;
  let totalsY = finalY + 10;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");

  if (pricing.couponDiscountAmount > 0) {
    doc.text(`Subtotal: ${formatPdfCurrency(pricing.taxableSubtotal + pricing.couponDiscountAmount)}`, pageWidth - 14, totalsY, {
      align: "right",
    });
    totalsY += 6;
    doc.text(`Coupon: -${formatPdfCurrency(pricing.couponDiscountAmount)}`, pageWidth - 14, totalsY, {
      align: "right",
    });
    totalsY += 6;
  }

  doc.text(`Taxable subtotal: ${formatPdfCurrency(pricing.taxableSubtotal)}`, pageWidth - 14, totalsY, {
    align: "right",
  });
  totalsY += 6;

  if (pricing.taxAmount > 0) {
    doc.text(
      `Texas Sales Tax (${(pricing.taxRate * 100).toFixed(2)}%): ${formatPdfCurrency(pricing.taxAmount)}`,
      pageWidth - 14,
      totalsY,
      { align: "right" }
    );
    totalsY += 6;
  }

  if (pricing.shippingAmount >= 0) {
    doc.text(
      `Shipping & Delivery: ${pricing.shippingIsFree ? "$0.00 (Free)" : formatPdfCurrency(pricing.shippingAmount)}`,
      pageWidth - 14,
      totalsY,
      { align: "right" }
    );
    totalsY += 6;
  }

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(
    `Total: ${formatPdfCurrency(order.totalPrice)}`,
    pageWidth - 14,
    totalsY + 4,
    { align: "right" }
  );

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120);
  doc.text(
    `Generated by ${company.name || "Cabinetto Pro"} Admin Panel`,
    14,
    doc.internal.pageSize.getHeight() - 10
  );

  return doc;
}

export function downloadOrderPdf(order: OrderWithCustomer) {
  const doc = buildOrderPdfDocument(order);
  doc.save(`order-${order.id}-quote.pdf`);
}

export function getOrderPdfBlob(order: OrderWithCustomer) {
  const doc = buildOrderPdfDocument(order);
  return doc.output("blob");
}
