"use client";

import Link from "next/link";
import { useCallback, useMemo, useState } from "react";
import { AdminShell } from "@/components/admin/AdminShell";
import { AdminSectionNav } from "@/components/admin/AdminOrdersSubNav";
import { AdminOrdersStatCard } from "@/components/admin/AdminOrdersStatCard";
import { LoadingState } from "@/components/ui/LoadingState";
import { SearchIcon } from "@/components/ui/Icon";
import { useDeferredEffect } from "@/hooks/useDeferredEffect";
import { useDebouncedValue } from "@/hooks/useDebouncedValue";
import { formatPrice } from "@/lib/order-display";
import { ui } from "@/lib/ui-classes";
import {
  CLIENT_QUOTE_STATUS_LABELS,
  type AdminClientQuoteSummary,
  type ClientQuoteStatus,
} from "@/types/client-quotes";

function formatDate(value: string) {
  return new Intl.DateTimeFormat("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date(value));
}

function statusBadgeClass(status: ClientQuoteStatus) {
  switch (status) {
    case "CONVERTED":
      return "bg-emerald-100 text-emerald-800 dark:bg-emerald-950/50 dark:text-emerald-300";
    case "EXPIRED":
      return "bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300";
    default:
      return "bg-amber-100 text-amber-800 dark:bg-amber-950/50 dark:text-amber-300";
  }
}

function dealerLabel(quote: AdminClientQuoteSummary) {
  return quote.dealerCompanyName?.trim() || quote.dealerContactName?.trim() || quote.dealerEmail;
}

export default function AdminDealerQuotesPage() {
  const [quotes, setQuotes] = useState<AdminClientQuoteSummary[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [searchInput, setSearchInput] = useState("");
  const debouncedSearch = useDebouncedValue(searchInput, 300);

  const loadQuotes = useCallback(async () => {
    setIsLoading(true);
    setError(null);

    try {
      const response = await fetch("/api/admin/client-quotes");

      if (!response.ok) {
        const payload = (await response.json().catch(() => null)) as { error?: string } | null;
        throw new Error(payload?.error ?? "Failed to load dealer client quotes");
      }

      const data = (await response.json()) as { quotes: AdminClientQuoteSummary[] };
      setQuotes(data.quotes);
    } catch (loadError) {
      setError(
        loadError instanceof Error ? loadError.message : "Failed to load dealer client quotes"
      );
    } finally {
      setIsLoading(false);
    }
  }, []);

  useDeferredEffect(() => {
    void loadQuotes();
  }, [loadQuotes]);

  const filteredQuotes = useMemo(() => {
    const query = debouncedSearch.trim().toLowerCase();

    if (!query) {
      return quotes;
    }

    return quotes.filter((quote) => {
      const haystack = [
        quote.clientName,
        quote.clientEmail ?? "",
        dealerLabel(quote),
        quote.dealerEmail,
        CLIENT_QUOTE_STATUS_LABELS[quote.status],
      ]
        .join(" ")
        .toLowerCase();

      return haystack.includes(query);
    });
  }, [debouncedSearch, quotes]);

  const pipelineStats = useMemo(() => {
    const pending = quotes.filter((quote) => quote.status === "PENDING");
    const converted = quotes.filter((quote) => quote.status === "CONVERTED");

    return {
      totalQuotes: quotes.length,
      pendingCount: pending.length,
      pendingValue: pending.reduce((sum, quote) => sum + quote.totalAmount, 0),
      convertedCount: converted.length,
      convertedValue: converted.reduce((sum, quote) => sum + quote.totalAmount, 0),
    };
  }, [quotes]);

  return (
    <AdminShell
      title="Dealer client quotes"
      subtitle="Monitor end-customer quotes generated by dealers for sales pipeline tracking."
      wide
    >
      <AdminSectionNav variant="orders" activeOrderTab="dealer-quotes" />

      <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <AdminOrdersStatCard label="Total quotes" value={String(pipelineStats.totalQuotes)} />
        <AdminOrdersStatCard
          label="Pending pipeline"
          value={String(pipelineStats.pendingCount)}
          hint={formatPrice(pipelineStats.pendingValue)}
          accent="amber"
        />
        <AdminOrdersStatCard
          label="Converted"
          value={String(pipelineStats.convertedCount)}
          hint={formatPrice(pipelineStats.convertedValue)}
          accent="emerald"
        />
        <AdminOrdersStatCard
          label="Unique dealers"
          value={String(new Set(quotes.map((quote) => quote.userId)).size)}
          accent="blue"
        />
      </div>

      <div className={`mb-6 flex flex-wrap items-center gap-3 ${ui.adminCard}`}>
        <div className="relative min-w-[240px] flex-1">
          <SearchIcon size={16} className="pointer-events-none absolute top-1/2 left-3 -translate-y-1/2 text-slate-400" />
          <input
            type="search"
            value={searchInput}
            onChange={(event) => setSearchInput(event.target.value)}
            placeholder="Search dealer, client, or status..."
            className={`${ui.input} w-full pl-9`}
          />
        </div>
      </div>

      {isLoading ? (
        <LoadingState label="Loading dealer client quotes..." minHeight="min-h-[320px]" spinnerSize="lg" />
      ) : error ? (
        <div className="rounded-2xl border border-red-200 bg-red-50 px-6 py-8 text-center dark:border-red-900/40 dark:bg-red-950/30">
          <p className="text-red-700 dark:text-red-300">{error}</p>
          <button type="button" onClick={() => void loadQuotes()} className={`mt-4 ${ui.btnPrimary}`}>
            Retry
          </button>
        </div>
      ) : filteredQuotes.length === 0 ? (
        <div className={`px-6 py-12 text-center ${ui.emptyState}`}>
          <p className="text-base font-semibold text-slate-900 dark:text-cream">No dealer quotes found</p>
          <p className={`mt-2 ${ui.bodyMuted}`}>
            Quotes appear here when dealers generate client PDFs from their cart.
          </p>
        </div>
      ) : (
        <div className={`overflow-x-auto ${ui.adminCard}`}>
          <table className="min-w-full text-left text-sm">
            <thead className="border-b border-slate-200/80 text-xs uppercase tracking-wide text-slate-500 dark:border-slate-700/80">
              <tr>
                <th className="px-4 py-3 font-semibold">Date</th>
                <th className="px-4 py-3 font-semibold">Dealer</th>
                <th className="px-4 py-3 font-semibold">End client</th>
                <th className="px-4 py-3 font-semibold">Items</th>
                <th className="px-4 py-3 font-semibold">Total</th>
                <th className="px-4 py-3 font-semibold">Status</th>
              </tr>
            </thead>
            <tbody>
              {filteredQuotes.map((quote) => (
                <tr
                  key={quote.id}
                  className="border-b border-slate-100 last:border-b-0 dark:border-slate-800"
                >
                  <td className="px-4 py-3 whitespace-nowrap">{formatDate(quote.createdAt)}</td>
                  <td className="px-4 py-3">
                    <p className="font-medium text-slate-900 dark:text-cream">{dealerLabel(quote)}</p>
                    <p className="text-xs text-slate-500 dark:text-slate-400">{quote.dealerEmail}</p>
                    <Link
                      href={`/admin/users?search=${encodeURIComponent(quote.dealerEmail)}`}
                      className="text-xs text-brand hover:underline"
                    >
                      View dealer
                    </Link>
                  </td>
                  <td className="px-4 py-3">
                    <p className="font-medium text-slate-900 dark:text-cream">{quote.clientName}</p>
                    {quote.clientEmail && (
                      <p className="text-xs text-slate-500 dark:text-slate-400">{quote.clientEmail}</p>
                    )}
                  </td>
                  <td className="px-4 py-3">{quote.itemCount}</td>
                  <td className="px-4 py-3 font-medium">{formatPrice(quote.totalAmount)}</td>
                  <td className="px-4 py-3">
                    <span
                      className={`inline-flex rounded-full px-2.5 py-0.5 text-xs font-semibold ${statusBadgeClass(quote.status)}`}
                    >
                      {CLIENT_QUOTE_STATUS_LABELS[quote.status]}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </AdminShell>
  );
}
